version: '3.8'
services:
  proficiency-test:
    build: .
    ports:
      - "8000:8000"
      - "8001:8001"
    environment:
      - MONGO_URL=mongodb://mongo-db:27017
    depends_on:
      - mongo-db
    volumes:
    - ./outputs:/app/outputs:Z
    - ./database:/app/database:Z
  mongo-db:
    image: mongo:latest
    ports:
      - "27017:27017"